<?php
?>
<div class="page-title">
    <h1><?= __('This is a demo version please buy pro version on www.madit.fr'); ?></h1>
    <a href="https://www.madit.fr/shop/product/worldline-sips2-module-for-magento-2-6"><img src="https://www.madit.fr/r/sips2-logo"></a>
    <h1><?= ($block->getTitle()) ? $block->getTitle() : __('An error occurred in the process of payment'); ?></h1>
</div>
<?php if ($block->getMessage()): ?>
    <p><?= $block->getMessage(); ?></p>
<?php endif; ?>
<p><a href="/"><?= __("Retour à l\'acceuil.") ?></a></p>
