name: m2-actions-sips2-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 tests & build'
    steps:
      #- name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
      #  run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
      - uses: actions/checkout@v2

      - name: 'phpcs testing'
        uses: MAD-I-T/magento-actions@v3.10
        with:
          override_settings: 1
          process: 'phpcs-test'
          extension: 'Madit/Atos/'
          severity: 10
          standard: 'Magento2'
