name: m2-actions-sips2-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 tests & build'
    steps:
      #- name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
      #  run: find /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: 'install fresh magento repo'
        if: ${{true}}
        uses: MAD-I-T/magento-actions@v3.10
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'create-project'
          magento_version: 2.4.4
          no_push: 1   ## add this arg to not push to the repo ideal for quick test on specific version

      - name: 'launch magento2 unit test'
        uses: MAD-I-T/magento-actions@v3.10
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'unit-test'
          unit_test_subset_path: 'app/code/Madit/Sips2/Test/Unit'
          override_settings: 1

      - name: 'phpcs testing'
        uses: MAD-I-T/magento-actions@v3.10
        with:
          override_settings: 1
          process: 'phpcs-test'
          extension: 'Madit/Sips2/'
          severity: 10
          standard: 'Magento2'
